title: OptiRad Documentation
email: optiradsupport@hexarad.com
description: >-
  Opitrad, helping radiology departments put patients first.
baseurl: "" # e.g. /blog
url: https://optirad-docs.netlify.app
include:
  - admin
collections:
  docs:
    output: true
    relative_directory: _docs/
  categories:
    relative_directory: _categories/
sass:
  sass_dir: _sass
  quiet_deps: true
defaults:
  - scope:
      path: "_docs"
    values:
      layout: post
      permalink: /docs/:title:output_ext

plugins:
 - jekyll-remote-theme
remote_theme: jekyll/minima
theme: minima
show_excerpts: true
author:
  name: OptiRad Support
  email: optiradsupport@hexarad.com
