title: Optirad Documentation
email: opitrad-support@hexarad.com
description: >-
  Opitrad streamlines the scheduling of rediology departments
  taking into account each organisations requirements. Therefore
  a number of features require documentation, that documentionation
  lives here.
baseurl: "/docs" # e.g. /blog
url: "" # e.g. http://example.com
theme: minima



