title: Optirad Documentation
email: opitrad-support@hexarad.com
description: >-
  Opitrad, helping rediology departments put patients first.
baseurl: "" # e.g. /blog
url: "" # e.g. http://example.com
include:
  - admin
collections:
  docs:
    output: true
sass:
  sass_dir: _sass
  quiet_deps: true
defaults:
  - scope:
      path: "_docs"
    values:
      layout: post
      permalink: /docs/:title:output_ext

plugins:
 - jekyll-remote-theme
remote_theme: jekyll/minima
theme: minima
show_excerpts: true
author:
  name: Optirad Support
  email: optirad-support@hexarad.com
