backend:
  name: git-gateway
  branch: main

#publish_mode: editorial_workflow
media_folder: "assets/images/uploads"

collections:
  - name: 'docs'
    label: 'Docs' # Used in the UI
    label_singular: 'Doc' # Used in the UI, ie: "New Post"
    description: >
      A page of documentation that is listed under the chosen category
      and becomes its own page and url which can be linked to.
    folder: '_docs'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}} -- {{category}}'
    create: true # Allow users to create new documents in this collection
    view_groups:
      - label: Category
        field: string
    sortable_fields:
      - category
      - title
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        searchFields: ["category_name"]
        valueField: "category_name"
        multiple: false
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

  - name: categories
    label: Categories
    label_singular: Category
    description: >
      A category is shown as a heading within the documentation and is used to group
      links to the documents.
    folder: _categories/
    create: true
    identifier_field: category_name
    sortable_fields:
      - order
      - category_name
    fields:
      - { label: Name, name: category_name, widget: string }
      - { label: Order, name: order, widget: "number", value_type: "int", min: 0, step: 1, default: 100 }
