backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
publish_mode: editorial_workflow

collections:
  - name: 'docs'
    label: 'Docs' # Used in the UI
    label_singular: 'Doc' # Used in the UI, ie: "New Post"
    description: >
      A page of documentation
    folder: '_docs'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Date', name: 'date', widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
